/*
=======================================================================================
SCHEMA DO BANCO DE DADOS - AVIVAR ERP (VERSÃO FINAL)
=======================================================================================
*/
-- CREATE DATABASE PRODUCAO_ERP;
USE PRODUCAO_ERP;

-- ==================================================
-- 1. SEGURANÇA E ACESSO
-- ==================================================
CREATE TABLE IF NOT EXISTS
  USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_USUARIO VARCHAR(100) NOT NULL,
    EMAIL_USUARIO VARCHAR(100) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR(255) NOT NULL, -- Hash (Bcrypt/Argon2)
    PERFIL_USUARIO ENUM('ADMIN', 'PRODUCAO', 'ARTES', 'FINANCEIRO') NOT NULL DEFAULT 'PRODUCAO',
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

-- ==================================================
-- 2. CATÁLOGO DE PRODUTOS
-- ==================================================
CREATE TABLE IF NOT EXISTS
  CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(100) NOT NULL UNIQUE
  );

CREATE TABLE IF NOT EXISTS
  PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    SKU_PRODUTO VARCHAR(50) NOT NULL UNIQUE,
    NOME_PRODUTO VARCHAR(255) NOT NULL,
    DESC_PRODUTO TEXT,
    PRECO_VENDA DECIMAL(10, 2) NOT NULL,
    CUSTO_MAO_OBRA DECIMAL(10, 2) DEFAULT 0.00,
    IMPOSTOS DECIMAL(5, 2) DEFAULT 0.00,
    ID_CATEGORIA INT NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
  );

-- ==================================================
-- 3. ESTOQUE E ENGENHARIA (MATÉRIA-PRIMA)
-- ==================================================
CREATE TABLE IF NOT EXISTS
  MATERIA_PRIMA (
    ID_MATERIA INT AUTO_INCREMENT PRIMARY KEY,
    SKU_MATERIA VARCHAR(50) NOT NULL UNIQUE,
    NOME_MATERIA VARCHAR(255) NOT NULL,
    UNIDADE_MEDIDA VARCHAR(20) NOT NULL, -- Ex: KG, MT, UN, ML
    CUSTO_UNITARIO DECIMAL(10, 2) NOT NULL,
    SALDO_ESTOQUE DECIMAL(10, 3) DEFAULT 0.000,
    ESTOQUE_MINIMO DECIMAL(10, 3) DEFAULT 5.000,
    FORNECEDOR VARCHAR(255)
  );

-- Vínculo Produto <-> Insumo (Receita do Bolo)
CREATE TABLE IF NOT EXISTS
  FICHA_TECNICA (
    ID_FICHA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_MATERIA INT NOT NULL,
    QTD_CONSUMO DECIMAL(10, 4) NOT NULL, -- Precisão aumentada para insumos pequenos (ex: tinta)
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO) ON DELETE CASCADE,
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA_PRIMA (ID_MATERIA)
  );

-- Rastreabilidade (Kardex)
CREATE TABLE IF NOT EXISTS
  MOVIMENTO_ESTOQUE (
    ID_MOVIMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_MATERIA INT NOT NULL,
    TIPO_MOVIMENTO ENUM('ENTRADA', 'SAIDA_OP', 'AJUSTE', 'PERDA') NOT NULL,
    QTD_MOVIMENTADA DECIMAL(10, 4) NOT NULL,
    SALDO_ANTERIOR DECIMAL(10, 4) NOT NULL,
    SALDO_NOVO DECIMAL(10, 4) NOT NULL,
    ID_PEDIDO_REF INT NULL, -- Se foi gasto por uma OP, grava o ID do pedido
    DATA_MOVIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA_PRIMA (ID_MATERIA)
  );

CREATE TABLE IF NOT EXISTS
  COMPRA (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_MATERIA INT NOT NULL,
    DATA_COMPRA DATE NOT NULL,
    QTD_COMPRADA DECIMAL(10, 3) NOT NULL,
    CUSTO_TOTAL DECIMAL(10, 2) NOT NULL,
    OBSERVACOES TEXT,
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA_PRIMA (ID_MATERIA)
  );

-- ==================================================
-- 4. VENDAS E KANBAN
-- ==================================================
CREATE TABLE IF NOT EXISTS
  PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    NUM_PEDIDO_PLATAFORMA VARCHAR(100), -- ID da Shopee/ML
    PLATAFORMA_ORIGEM VARCHAR(50), -- Shopee, Site, WhatsApp
    NOME_CLIENTE VARCHAR(255),
    DATA_PEDIDO DATE NOT NULL,
    -- Financeiro
    VALOR_TOTAL DECIMAL(10, 2),
    LUCRO_ESTIMADO DECIMAL(10, 2),
    -- Controle Fiscal (Adicionados via Alter Table anteriormente)
    NF_EMITIDA BOOLEAN DEFAULT FALSE,
    NUM_NOTA_FISCAL VARCHAR(50) DEFAULT NULL,
    -- Controle de Produção
    RESPONSAVEL_PRODUCAO VARCHAR(255), -- Nome de quem pegou a tarefa
    STATUS_PEDIDO ENUM(
      'ENTRADA',
      'AGUARDANDO_ARTE',
      'CRIACAO',
      'IMPRIMINDO',
      'PRODUCAO',
      'ENVIADO',
      'CANCELADO'
    ) DEFAULT 'ENTRADA',
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS
  ITEM_PEDIDO (
    ID_ITEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
  );

-- ==================================================
-- 5. CHÃO DE FÁBRICA (PCP)
-- ==================================================
CREATE TABLE IF NOT EXISTS
  ORDEM_PRODUCAO (
    ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    RESPONSAVEL VARCHAR(100) NOT NULL, -- Operador que bipou
    DATA_INICIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_FIM DATETIME NULL,
    STATUS_OP ENUM('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA') DEFAULT 'ABERTA',
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
  );

/*--------- ARQUIVOS PEDIDOS ---------------------------------*/
CREATE TABLE IF NOT EXISTS
  ARQUIVO_PEDIDO (
    ID_ARQUIVO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    URL_ARQUIVO TEXT NOT NULL,
    TIPO_ARQUIVO VARCHAR(50),
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO) ON DELETE CASCADE
  );

/* ----------------- Despesas --------------- */
CREATE TABLE IF NOT EXISTS
  DESPESA (
    ID_DESPESA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    CATEGORIA VARCHAR(50), -- Ex: Fixa, Variável, Imposto
    DATA_VENCIMENTO DATE,
    PAGO BOOLEAN DEFAULT FALSE,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

-- ==================================================
-- 6. DADOS INICIAIS (SEED)
-- ==================================================
-- Categorias
INSERT INTO
  CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA)
VALUES
  (1, 'Canecas'),
  (2, 'Vestuário'),
  (3, 'Decoração'),
  (4, 'Kits') ON DUPLICATE KEY
UPDATE NOME_CATEGORIA = NOME_CATEGORIA;

-- Produtos Exemplo
INSERT INTO
  PRODUTO (
    SKU_PRODUTO,
    NOME_PRODUTO,
    DESC_PRODUTO,
    PRECO_VENDA,
    ID_CATEGORIA
  )
VALUES
  (
    'CAN-001',
    'Caneca Avivar Branca',
    'Caneca Cerâmica 325ml Branca',
    35.90,
    1
  ),
  (
    'CAN-002',
    'Caneca Mágica Preta',
    'Caneca Termossensível',
    45.00,
    1
  ),
  (
    'CAM-ROSA',
    'Camiseta Avivar Rosa',
    'Camiseta Algodão Premium',
    49.90,
    2
  ),
  (
    'AZU-15',
    'Azulejo 15x15',
    'Azulejo com suporte',
    15.00,
    3
  ) ON DUPLICATE KEY
UPDATE PRECO_VENDA =
VALUES
  (PRECO_VENDA);

-- Pedido Exemplo (Para teste da IA)
INSERT INTO
  PEDIDO (
    ID_PEDIDO,
    NOME_CLIENTE,
    NUM_PEDIDO_PLATAFORMA,
    DATA_PEDIDO,
    VALOR_TOTAL,
    STATUS_PEDIDO
  )
VALUES
  (
    9999,
    'Cliente Teste IA',
    'IA-001',
    NOW(),
    150.00,
    'ENVIADO'
  ) ON DUPLICATE KEY
UPDATE NOME_CLIENTE =
VALUES
  (NOME_CLIENTE);

ALTER TABLE ARQUIVO_PEDIDO
ADD COLUMN PUBLIC_ID VARCHAR(255);

ALTER TABLE PRODUTO
ADD COLUMN IMPOSTO_PERCENTUAL DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN MAO_DE_OBRA_VALOR DECIMAL(10, 2) DEFAULT 0;


-- Log de sincronia
CREATE TABLE HISTORICO_SINCRONIZACAO_SHOPEE (
  ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
  DATA_SINCRONIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
  TIPO_SINCRONIZACAO ENUM('auto', 'manual') NOT NULL,
  STATUS ENUM('sucesso', 'erro', 'parcial') NOT NULL,
  QTD_CRIADOS INT DEFAULT 0,
  QTD_DUPLICADOS INT DEFAULT 0,
  QTD_SKUS_INVALIDOS INT DEFAULT 0,
  REQUISICOES_USADAS INT DEFAULT 0,
  MENSAGEM TEXT
);